name: Build and deploy static app to Oracle Cloud VM - ChatAppUI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Step 3: Clean and build fresh dist files
      - name: Install dependencies and build
        run: |
          rm -rf dist
          npm ci
          npm run build --if-present

      # Step 4: Debug - Show local dist contents
      - name: Check dist contents
        run: ls -lah dist

      # Step 5: Clean remote folder before upload
      - name: Clean remote folder before upload
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/ubuntu/ChatUI
            rm -rf /home/ubuntu/ChatUI/*

      # Step 6: Upload built files to Oracle VM
      - name: Upload built files to Oracle Cloud VM
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          source: "./dist/*"
          target: "/home/ubuntu/ChatUI"
          strip_components: 1

      # Step 7: Deploy static files with NGINX
      - name: Deploy static files with NGINX
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          script: |
            # Install NGINX if not installed
            if ! command -v nginx >/dev/null 2>&1; then
              sudo apt-get update
              sudo apt-get install -y nginx
            fi

            # Clean old files from web root
            sudo rm -rf /var/www/html/*

            # Move new files to web root
            sudo cp -r /home/ubuntu/ChatUI/* /var/www/html/

            # Set correct permissions
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html

            # Restart NGINX
            sudo systemctl restart nginx

      # Step 8: Debug - Verify deployed files
      - name: Verify deployed files on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          script: ls -lah /var/www/html
