name: Build and deploy Node.js app to Oracle Cloud VM - ChatAppUI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip dist/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Upload release to Oracle Cloud VM
        run: |
          echo "${{ secrets.ORACLE_SSH_PRIVATE_KEY }}" > oracle_key.pem
          chmod 600 oracle_key.pem

          scp -i oracle_key.pem -o StrictHostKeyChecking=no release.zip ${{ secrets.ORACLE_VM_USER }}@${{ secrets.ORACLE_VM_IP }}:~/release.zip

      - name: Deploy app on Oracle Cloud VM
        run: |
          ssh -i oracle_key.pem -o StrictHostKeyChecking=no ${{ secrets.ORACLE_VM_USER }}@${{ secrets.ORACLE_VM_IP }} << 'EOF'
            # Install unzip if not present
            sudo apt-get update
            sudo apt-get install -y unzip

            # Prepare and deploy app
            mkdir -p ~/chatapp
            unzip -o ~/release.zip -d ~/chatapp
            cd ~/chatapp

            # Install dependencies (skip dev deps for production)
            npm install --omit=dev

            # Start/restart with PM2
            pm2 restart chatapp || pm2 start dist/index.js --name chatapp

            # Save PM2 state and generate startup script
            pm2 save
            pm2 startup systemd -u $USER --hp $HOME
          EOF
