name: Deploy to Oracle VM

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Save SSH private key
      run: |
        echo "${{ secrets.ORACLE_SSH_PRIVATE_KEY }}" > oracle_key.pem
        chmod 600 oracle_key.pem

    - name: Zip release files
      run: |
        zip -r release.zip dist

    - name: Upload release.zip to Oracle VM
      run: |
        scp -i oracle_key.pem -o StrictHostKeyChecking=no release.zip ${{ secrets.ORACLE_VM_USER }}@${{ secrets.ORACLE_VM_IP }}:/home/${{ secrets.ORACLE_VM_USER }}/release.zip

    - name: SSH into Oracle VM and deploy app
      run: |
        ssh -i oracle_key.pem -o StrictHostKeyChecking=no ${{ secrets.ORACLE_VM_USER }}@${{ secrets.ORACLE_VM_IP }} << 'EOF'
          sudo apt-get update
          sudo apt-get install -y unzip
          mkdir -p ~/chatapp
          unzip -o ~/release.zip -d ~/chatapp

          # Optional: if using NGINX
          # sudo cp -r ~/chatapp/dist/* /var/www/html/

          # Optional: restart NGINX if needed
          # sudo systemctl restart nginx
        EOF
